insert into favs (name, description, price) values ('Daren', 'Fire Protection', '3.71');
insert into favs (name, description, price) values ('Edlin', 'Soft Flooring and Base', '3.84');
insert into favs (name, description, price) values ('Giordano', 'Temp Fencing, Decorative Fencing and Gates', '8.94');
insert into favs (name, description, price) values ('Lemuel', 'EIFS', '2.42');
insert into favs (name, description, price) values ('Tulley', 'Wall Protection', '6.70');
insert into favs (name, description, price) values ('Thaxter', 'Elevator', '3.05');
insert into favs (name, description, price) values ('Bentlee', 'Exterior Signage', '3.42');
insert into favs (name, description, price) values ('Fair', 'Electrical and Fire Alarm', '4.78');
insert into favs (name, description, price) values ('Alwin', 'Site Furnishings', '1.79');
insert into favs (name, description, price) values ('Graig', 'Wall Protection', '5.59');
insert into favs (name, description, price) values ('Brian', 'HVAC', '2.59');
insert into favs (name, description, price) values ('Darnall', 'Asphalt Paving', '4.78');
insert into favs (name, description, price) values ('Vernen', 'Doors, Frames & Hardware', '6.66');
insert into favs (name, description, price) values ('Nickolaus', 'Electrical', '7.49');
insert into favs (name, description, price) values ('Zak', 'HVAC', '3.90');
insert into favs (name, description, price) values ('Sheffield', 'Structural and Misc Steel (Fabrication)', '8.86');
insert into favs (name, description, price) values ('Ezekiel', 'Casework', '7.35');
insert into favs (name, description, price) values ('Eduino', 'Electrical and Fire Alarm', '6.76');
insert into favs (name, description, price) values ('Hercule', 'Glass & Glazing', '9.30');
insert into favs (name, description, price) values ('Eldridge', 'Wall Protection', '2.16');
insert into favs (name, description, price) values ('Callean', 'Doors, Frames & Hardware', '9.30');
insert into favs (name, description, price) values ('Christoffer', 'RF Shielding', '4.56');
insert into favs (name, description, price) values ('Andrej', 'Termite Control', '9.86');
insert into favs (name, description, price) values ('Vassili', 'Roofing (Metal)', '6.23');
insert into favs (name, description, price) values ('Farleigh', 'Electrical', '0.97');
insert into favs (name, description, price) values ('Prent', 'Painting & Vinyl Wall Covering', '7.46');
insert into favs (name, description, price) values ('Levin', 'Exterior Signage', '5.69');
insert into favs (name, description, price) values ('Sully', 'Curb & Gutter', '7.17');
insert into favs (name, description, price) values ('Pierson', 'Doors, Frames & Hardware', '0.83');
insert into favs (name, description, price) values ('Coop', 'Construction Clean and Final Clean', '0.51');
insert into favs (name, description, price) values ('Vittorio', 'Termite Control', '3.47');
insert into favs (name, description, price) values ('Sayre', 'Fire Sprinkler System', '8.86');
insert into favs (name, description, price) values ('Burgess', 'Drilled Shafts', '0.71');
insert into favs (name, description, price) values ('Kurt', 'Painting & Vinyl Wall Covering', '6.29');
insert into favs (name, description, price) values ('Boyce', 'Elevator', '0.55');
insert into favs (name, description, price) values ('Lowe', 'Drilled Shafts', '5.75');
insert into favs (name, description, price) values ('Philbert', 'Roofing (Metal)', '4.08');
insert into favs (name, description, price) values ('Zackariah', 'Hard Tile & Stone', '6.84');
insert into favs (name, description, price) values ('Tull', 'Drywall & Acoustical (FED)', '9.94');
insert into favs (name, description, price) values ('Hugh', 'Retaining Wall and Brick Pavers', '3.82');
insert into favs (name, description, price) values ('Monty', 'Curb & Gutter', '8.04');
insert into favs (name, description, price) values ('Murvyn', 'EIFS', '8.76');
insert into favs (name, description, price) values ('Banky', 'Exterior Signage', '8.71');
insert into favs (name, description, price) values ('Beau', 'Roofing (Asphalt)', '8.05');
insert into favs (name, description, price) values ('Ingra', 'Doors, Frames & Hardware', '1.41');
insert into favs (name, description, price) values ('Kelvin', 'Fire Protection', '3.64');
insert into favs (name, description, price) values ('Lucian', 'Fire Protection', '0.91');
insert into favs (name, description, price) values ('Tybalt', 'Exterior Signage', '2.46');
insert into favs (name, description, price) values ('Westley', 'Termite Control', '9.21');
insert into favs (name, description, price) values ('Nikos', 'Glass & Glazing', '0.96');
