INSERT INTO items(name, description, price, tag, stock) VALUES ('cookie', 'rounded chocolate chip flavour', 1.50, 'chocolate, snack', 10);

insert into items (name, description, price, tag, stock) values ('Truffle Cups - Brown', 'Ornamental Railings', '14.68', 'Drama', 1);
insert into items (name, description, price, tag, stock) values ('Food Colouring - Pink', 'Asphalt Paving', '35.69', 'Comedy|Crime|Thriller', 2);
insert into items (name, description, price, tag, stock) values ('Garbage Bags - Clear', 'Fire Protection', '41.58', 'Action|Drama', 3);
insert into items (name, description, price, tag, stock) values ('Pork - Tenderloin, Frozen', 'Doors, Frames & Hardware', '20.56', 'Adventure|Drama', 4);
insert into items (name, description, price, tag, stock) values ('Rootbeer', 'Doors, Frames & Hardware', '44.19', 'War', 5);
insert into items (name, description, price, tag, stock) values ('Cheese Cloth No 100', 'Rebar & Wire Mesh Install', '34.23', 'Drama|Horror', 6);
insert into items (name, description, price, tag, stock) values ('Salt - Celery', 'Casework', '20.14', 'Drama', 7);
insert into items (name, description, price, tag, stock) values ('Stock - Beef, White', 'HVAC', '7.52', 'Comedy|Drama|Musical', 8);
insert into items (name, description, price, tag, stock) values ('Cattail Hearts', 'Ornamental Railings', '32.93', 'Drama', 9);
insert into items (name, description, price, tag, stock) values ('Tart Shells - Savory, 4', 'Rebar & Wire Mesh Install', '48.84', 'Crime|Drama', 10);
insert into items (name, description, price, tag, stock) values ('Sauce - Soya, Dark', 'Framing (Steel)', '21.40', 'Comedy', 11);
insert into items (name, description, price, tag, stock) values ('Cheese - Colby', 'Framing (Steel)', '10.58', 'Drama|Musical', 12);
insert into items (name, description, price, tag, stock) values ('Rum - Coconut, Malibu', 'Roofing (Metal)', '8.13', 'Crime|Thriller', 13);
insert into items (name, description, price, tag, stock) values ('Fennel', 'Exterior Signage', '24.81', 'Documentary', 14);
insert into items (name, description, price, tag, stock) values ('Wine - Alicanca Vinho Verde', 'Electrical', '39.70', 'Documentary', 15);
insert into items (name, description, price, tag, stock) values ('Swordfish Loin Portions', 'Prefabricated Aluminum Metal Canopies', '41.68', 'Comedy|Drama', 16);
insert into items (name, description, price, tag, stock) values ('Pepper - Green', 'Sitework & Site Utilities', '27.73', 'Comedy', 17);
insert into items (name, description, price, tag, stock) values ('Celery Root', 'RF Shielding', '10.90', 'Comedy|Romance', 18);
insert into items (name, description, price, tag, stock) values ('Bread - Multigrain Oval', 'Doors, Frames & Hardware', '16.51', 'Documentary', 19);
insert into items (name, description, price, tag, stock) values ('Sprouts - Brussel', 'Drilled Shafts', '16.09', 'Action|Comedy', 20);
insert into items (name, description, price, tag, stock) values ('Pasta - Fusili Tri - Coloured', 'Doors, Frames & Hardware', '40.07', 'Crime|Drama', 21);
insert into items (name, description, price, tag, stock) values ('Wine - Red, Mouton Cadet', 'Fire Sprinkler System', '9.69', 'Horror', 22);
insert into items (name, description, price, tag, stock) values ('Pepper - Gypsy Pepper', 'Rebar & Wire Mesh Install', '17.49', 'Action|Adventure', 23);
insert into items (name, description, price, tag, stock) values ('Kale - Red', 'Drilled Shafts', '6.17', 'Adventure|Comedy', 24);
insert into items (name, description, price, tag, stock) values ('Initation Crab Meat', 'Painting & Vinyl Wall Covering', '46.81', 'Drama', 25);
insert into items (name, description, price, tag, stock) values ('Beef - Top Sirloin', 'Temp Fencing, Decorative Fencing and Gates', '40.21', 'Drama|Romance', 26);
insert into items (name, description, price, tag, stock) values ('Ice Cream - Fudge Bars', 'EIFS', '43.54', 'Comedy', 27);
insert into items (name, description, price, tag, stock) values ('Parsnip', 'HVAC', '19.10', 'Adventure|Crime|Drama', 28);
insert into items (name, description, price, tag, stock) values ('Sorrel - Fresh', 'Prefabricated Aluminum Metal Canopies', '10.80', 'Action|Crime|Thriller', 29);
insert into items (name, description, price, tag, stock) values ('Beef - Baby, Liver', 'Fire Sprinkler System', '47.15', 'Comedy|Romance', 30);
insert into items (name, description, price, tag, stock) values ('Yoghurt Tubes', 'RF Shielding', '0.46', 'Sci-Fi|Thriller|IMAX', 31);
insert into items (name, description, price, tag, stock) values ('Cheese - Provolone', 'Granite Surfaces', '30.91', 'Animation|Comedy|Fantasy', 32);
insert into items (name, description, price, tag, stock) values ('Sauce - Chili', 'Fire Sprinkler System', '44.20', 'Adventure|Children|Fantasy', 33);
insert into items (name, description, price, tag, stock) values ('Mangostein', 'EIFS', '15.44', 'Drama|Romance', 34);
insert into items (name, description, price, tag, stock) values ('Bread - Corn Muffaleta Onion', 'Termite Control', '47.69', 'Adventure|Drama|Romance', 35);
insert into items (name, description, price, tag, stock) values ('Bowl 12 Oz - Showcase 92012', 'Landscaping & Irrigation', '33.14', 'Comedy|Drama', 36);
insert into items (name, description, price, tag, stock) values ('Bread - Flat Bread', 'Masonry & Precast', '31.33', 'Action|Adventure|Thriller', 37);
insert into items (name, description, price, tag, stock) values ('Arizona - Plum Green Tea', 'Elevator', '5.88', 'Comedy|Crime|Drama', 38);
insert into items (name, description, price, tag, stock) values ('Sauce - Caesar Dressing', 'EIFS', '13.23', 'Comedy|Drama', 39);
insert into items (name, description, price, tag, stock) values ('Pasta - Penne, Rigate, Dry', 'Rebar & Wire Mesh Install', '44.75', 'Western', 40);
insert into items (name, description, price, tag, stock) values ('Oven Mitt - 13 Inch', 'Granite Surfaces', '37.44', 'Horror|Thriller', 41);
insert into items (name, description, price, tag, stock) values ('Fruit Salad Deluxe', 'Waterproofing & Caulking', '24.73', 'Comedy', 42);
insert into items (name, description, price, tag, stock) values ('Compound - Raspberry', 'Roofing (Asphalt)', '19.44', 'Comedy|Fantasy', 43);
insert into items (name, description, price, tag, stock) values ('Dried Cranberries', 'Prefabricated Aluminum Metal Canopies', '19.65', '(no genres listed)', 44);
insert into items (name, description, price, tag, stock) values ('Turnip - Mini', 'RF Shielding', '15.04', 'Crime|Film-Noir', 45);
insert into items (name, description, price, tag, stock) values ('Cucumber - English', 'Drywall & Acoustical (FED)', '12.77', 'Sci-Fi|Thriller', 46);
insert into items (name, description, price, tag, stock) values ('Bay Leaf Ground', 'Painting & Vinyl Wall Covering', '38.62', 'Action|Thriller', 47);
insert into items (name, description, price, tag, stock) values ('Scotch - Queen Anne', 'Masonry & Precast', '48.38', 'Drama|Romance', 48);
insert into items (name, description, price, tag, stock) values ('Coffee Decaf Colombian', 'Drywall & Acoustical (MOB)', '40.12', 'Comedy|Crime', 49);
insert into items (name, description, price, tag, stock) values ('Carbonated Water - Raspberry', 'Overhead Doors', '11.06', 'Documentary', 50);
insert into items (name, description, price, tag, stock) values ('Beer - Camerons Auburn', 'Drywall & Acoustical (MOB)', '30.63', 'Documentary', 51);
insert into items (name, description, price, tag, stock) values ('Beef - Top Butt Aaa', 'Prefabricated Aluminum Metal Canopies', '2.27', 'Animation|Fantasy|Sci-Fi|Thriller', 52);
insert into items (name, description, price, tag, stock) values ('Rosemary - Dry', 'Hard Tile & Stone', '34.11', 'Adventure|War|Western', 53);
insert into items (name, description, price, tag, stock) values ('Juice - Apple, 500 Ml', 'Construction Clean and Final Clean', '45.73', 'Drama', 54);
insert into items (name, description, price, tag, stock) values ('Clam Nectar', 'Curb & Gutter', '34.75', 'Drama', 55);
insert into items (name, description, price, tag, stock) values ('Goldschalger', 'Plumbing & Medical Gas', '46.61', 'Comedy', 56);
insert into items (name, description, price, tag, stock) values ('Oil - Food, Lacquer Spray', 'Masonry & Precast', '12.00', 'Animation|Comedy|Musical', 57);
insert into items (name, description, price, tag, stock) values ('Tofu - Soft', 'Exterior Signage', '4.67', 'Drama|War', 58);
insert into items (name, description, price, tag, stock) values ('Tortillas - Flour, 12', 'Waterproofing & Caulking', '26.27', 'Comedy|Fantasy|Romance', 59);
insert into items (name, description, price, tag, stock) values ('Apple - Fuji', 'Ornamental Railings', '8.34', 'Drama', 60);
insert into items (name, description, price, tag, stock) values ('Lobster - Tail, 3 - 4 Oz', 'Casework', '2.16', 'Sci-Fi', 61);
insert into items (name, description, price, tag, stock) values ('Spice - Greek 1 Step', 'Fire Sprinkler System', '10.81', 'Comedy|Romance', 62);
insert into items (name, description, price, tag, stock) values ('Flour - Pastry', 'Elevator', '17.68', 'Drama', 63);
insert into items (name, description, price, tag, stock) values ('Beef - Ground Lean Fresh', 'Fire Protection', '5.96', 'Comedy|Romance', 64);
insert into items (name, description, price, tag, stock) values ('Bread - Roll, Canadian Dinner', 'Temp Fencing, Decorative Fencing and Gates', '0.17', 'Horror|Thriller', 65);
insert into items (name, description, price, tag, stock) values ('Bar Mix - Lime', 'Drywall & Acoustical (MOB)', '5.28', 'Comedy|Romance', 66);
insert into items (name, description, price, tag, stock) values ('Muffin Mix - Lemon Cranberry', 'Ornamental Railings', '37.92', 'Drama', 67);
insert into items (name, description, price, tag, stock) values ('Dc - Frozen Momji', 'HVAC', '47.57', 'Comedy|Romance', 68);
insert into items (name, description, price, tag, stock) values ('Soup - Campbells, Lentil', 'Electrical', '19.84', 'Documentary', 69);
insert into items (name, description, price, tag, stock) values ('Spaghetti Squash', 'Construction Clean and Final Clean', '10.75', 'Children|Comedy', 70);
insert into items (name, description, price, tag, stock) values ('Pail With Metal Handle 16l White', 'Electrical and Fire Alarm', '29.82', 'Drama', 71);
insert into items (name, description, price, tag, stock) values ('Sterno - Chafing Dish Fuel', 'Sitework & Site Utilities', '10.12', 'Comedy|Romance', 72);
insert into items (name, description, price, tag, stock) values ('Tilapia - Fillets', 'Asphalt Paving', '22.83', 'Documentary', 73);
insert into items (name, description, price, tag, stock) values ('Sauce - Thousand Island', 'Termite Control', '14.12', 'Adventure|Children|Fantasy', 74);
insert into items (name, description, price, tag, stock) values ('Veal - Bones', 'Electrical and Fire Alarm', '11.28', 'Comedy|Drama', 75);
insert into items (name, description, price, tag, stock) values ('Wine - Sogrape Mateus Rose', 'Plumbing & Medical Gas', '32.63', 'Animation', 76);
insert into items (name, description, price, tag, stock) values ('Juice - Pineapple, 48 Oz', 'Waterproofing & Caulking', '23.99', 'Action|Romance|Sci-Fi', 77);
insert into items (name, description, price, tag, stock) values ('Wine - Beringer Founders Estate', 'Painting & Vinyl Wall Covering', '2.74', 'Horror|Sci-Fi', 78);
insert into items (name, description, price, tag, stock) values ('Chocolate - Sugar Free Semi Choc', 'Wall Protection', '42.20', 'Action|Adventure|Animation|Children|Comedy|Sci-Fi', 79);
insert into items (name, description, price, tag, stock) values ('Juice - Propel Sport', 'Granite Surfaces', '6.89', 'Drama', 80);
insert into items (name, description, price, tag, stock) values ('Pork - Smoked Kassler', 'Electrical and Fire Alarm', '4.18', 'Drama', 81);
insert into items (name, description, price, tag, stock) values ('Snails - Large Canned', 'Fire Protection', '3.66', 'Action', 82);
insert into items (name, description, price, tag, stock) values ('Red Pepper Paste', 'Painting & Vinyl Wall Covering', '33.49', 'Horror|Thriller', 83);
insert into items (name, description, price, tag, stock) values ('Appetizer - Cheese Bites', 'Wall Protection', '10.38', 'Drama|Romance', 84);
insert into items (name, description, price, tag, stock) values ('Scampi Tail', 'Sitework & Site Utilities', '25.10', 'Comedy|Drama|Romance', 85);
insert into items (name, description, price, tag, stock) values ('Beef - Ox Tail, Frozen', 'Site Furnishings', '33.57', 'Comedy|Musical|Romance', 86);
insert into items (name, description, price, tag, stock) values ('Flax Seed', 'Prefabricated Aluminum Metal Canopies', '8.53', 'Comedy|Romance', 87);
insert into items (name, description, price, tag, stock) values ('Wine - Peller Estates Late', 'Wall Protection', '49.96', 'Mystery|Thriller', 88);
insert into items (name, description, price, tag, stock) values ('Oil - Olive', 'Structural & Misc Steel Erection', '26.80', 'Drama|Fantasy|War', 89);
insert into items (name, description, price, tag, stock) values ('Pepper - Chillies, Crushed', 'Painting & Vinyl Wall Covering', '25.36', 'Comedy|Romance', 90);
insert into items (name, description, price, tag, stock) values ('Juice - Tomato, 48 Oz', 'Epoxy Flooring', '18.34', 'Comedy|Thriller', 91);
insert into items (name, description, price, tag, stock) values ('Beets', 'Sitework & Site Utilities', '46.72', 'Comedy|Horror|Thriller', 92);
insert into items (name, description, price, tag, stock) values ('Rabbit - Whole', 'Drywall & Acoustical (MOB)', '26.69', 'Crime|Drama|Mystery', 93);
insert into items (name, description, price, tag, stock) values ('Nut - Walnut, Pieces', 'Painting & Vinyl Wall Covering', '32.33', 'Drama|Horror|Mystery|Thriller|War', 94);
insert into items (name, description, price, tag, stock) values ('Beer - Muskoka Cream Ale', 'Waterproofing & Caulking', '5.51', 'Action|Sci-Fi|Thriller', 95);
insert into items (name, description, price, tag, stock) values ('Pepper - Scotch Bonnet', 'Casework', '11.26', 'Action|Adventure|Crime|Drama|Romance', 96);
insert into items (name, description, price, tag, stock) values ('Nectarines', 'Marlite Panels (FED)', '33.73', 'Drama|Thriller', 97);
insert into items (name, description, price, tag, stock) values ('Skirt - 29 Foot', 'HVAC', '1.82', 'Comedy|Drama', 98);
insert into items (name, description, price, tag, stock) values ('Beef - Texas Style Burger', 'Curb & Gutter', '1.53', 'Crime|Film-Noir|Mystery|Thriller', 99);
insert into items (name, description, price, tag, stock) values ('Wine - Red, Black Opal Shiraz', 'Casework', '19.55', 'Comedy|Drama', 100);
