INSERT INTO items(name, description, ingredients, price, dietary, stock) VALUES ('Oreo Cookie Sandwich Biscuit - Chocolate', 'Rich, smooth chocolate cream sandwiched between two crunchy chocolate cookies.', 'Sugar, Wheat Flour, Non-Hydrogenated Vegetable Oil, Cocoa Powder (5%)', 3.30, 'halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Quaker Oats Oatmeal Cookies - Raisins', 'Quaker Oats in a delicious cookie', 'combining taste and nutrition, now you dont have to find excuses to snack anymore. Power your day with Quaker. With wholegrain oats.', 2.87, 'halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Chipsmore Cookies Mini - Original', 'Chocolate Chip cookies Original Flavour', 'Wheat Flour, Chocolate Chips (Sugars, Hydrogenated Vegetable Fat (Shea, Palm), Cocoa Powder, Cocoa Mass, Flavours, Dextrose', 4.60, 'halal', 2);
insert into items (name, description, ingredients, price, dietary, stock) values ('Kjeldsens Cookies Tin - Butter', 'Use only high quality, carefully selected ingredients. Crafted from a secret, time-honored recipe. Fragrant and buttery taste', 'Wheat Flour, Butter (27%), Sugar, Desiccated Coconut', 10.55, 'none', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Cowhead Sandwich Crackers with Calcium - Cheese', 'With calcium.', 'Wheat Flour, Vegetable Oil (Palm Oil), White Compound, Full Cream Milk Powder, Sugar, Cheese Powder, Maltodextrin, Salt, Calcium Carbonate', 2.40 , 'none', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Lotus Biscoff Biscuit - Original Caramalised', ' Made with a handful of natural ingredients. Vegan friendly, made with RSPO certified palm oil.', 'Wheat flour, Sugar, Vegetable oils, Candy Sugar Syrup, Raising agent' , 4.40, 'Vegan', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Naturel Cooking Oil - Premium Blend of Canola & Sunflower', ' Premium blend high in monounsaturates. Naturally cholestrol free. Contains omega 3 and 6', 'Canola and Sunflower Seeds Oil' , 8.95, 'Halal, Trans-Fat Free, Vegetarian', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Medella Organic Premium Coconut Cooking Oil', ' 100% natural and pure unhydrogenated. No chemicals nor solvent used. Rich in healthy medium chain fatty acid. Suitable for deep frying or taken orally as a supplement.','coconut, oil' ,17.97, 'Halal, Organic', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Milo Chocolate Malt Milk UHT Packet Drink', 'MILO® UHT Chocolate Malt Milk Drink is a ready to drink breakfast beverage with the natural goodness of malt barley, milk, cocoa, and Activ-Go', 'Skimmed Milk Powder, Malt Extract, Sugar, Cocoa, Palm Olein' , 14.80, 'Healthier Choice', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Coca-Cola Can Drink - Zero Sugar', 'Coca-Cola Zero offers consumers a zero Sugar alternative to their favourite Coca-Cola.', 'Carbonated Water, Caramel Colour, Phosphoric Acid, Sweeteners, Flavourings, Preservative ', 9.85, 'Healthier Choice', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Yakult Cultured Milk Bottle Drink - Assorted Flavours (Twin Pack)', 'Yakult drink containing healthy pre-biotics and pro-biotics', ' Lacticaseibacillus casei Shirota' , 6.80, 'Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Ribena Blackcurrant Fruit Packet Drink - Less Sweet', 'Rich in vitamin C. No artificial colours, flavours, sweeteners', 'Water, Sugar, Blackcurrant Juice, Maltodextrin, Citric Acid, Vitamin C', 3.80, 'Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Bake King Flours - Plain (All Purpose)', 'Selected from premium wheat. High in protein. Excellent for all varieties of bread and bun.Suitable for all types of bread machines', 'All purpose flour', 2.78, 'Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('FairPrice Plain Flour', 'FAIRPRICE PLAIN FLOUR 1KG', '100% Flour', 1.97, 'Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Tai Sun Flour Vermicelli', 'Get ready boiling stock put in Tai Sun Flour Vermicelli garnished according to your own choice', 'Wheat Flour, Salt, Water', 1.66, 'Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('SIX FORTUNE Shredded Flour Noodles 300 G', 'Traditional chinese plain shredded thick noodles that pair up perfectly with any sauce or stock to create a quick but tasty treat', 'Pure flour noodles', 3.95, 'Halal, Vegan', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Kelloggs Cereal - Cornflakes (Jumbo Pack)', 'Pour Kelloggs Cornflakes onto bowl with cold milkReady to serve', 'real corn, flour, oats', 5.30, 'Vegetarian, Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Nestle Cereal - Koko Krunch', 'All this wholegrain goodness with our signature great chocolatey taste, makes for a nutritious breakfast to refuel your kid', 'Cereal Grains [Wholegrain wheat (36.8%), Wheat Flour (gluten), Corn Semolina], Sugar, Fat-reduced Cocoa Powder, Barley Malt Extract', 5.00, 'Halal, Healthier Choice', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Nestle Cereal - Honey Stars Econopack', 'Delicious star-shaped pieces of goodness', 'honey, flour, oat', 7.97, 'Halal, Healthier Choice', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Nestle Cerelac Infant Cereal - Brown Rice & Milk', 'Cerelac is the first and only infant cereals with BIFIDUS BL probiotics which helps to fight against harmful bacteria, thereby maintaining a healthy digestive system.', 'Skimmed Milk Powder, Red Rice, Sugar Vegetable oils Maltodextrin, Minerals' , 6.97, 'Halal', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Friso Gold Milk Cereal Drink Powder - Wheat Based', 'For babies 6 months onwards, after they have grown used to rice based cereal.', 'Whole Milk, Skimmed Milk, Wheat Flour, Saccharose, Malt Extract, Maltodextrin, Galacto-Oligosaccharides, Thickener', 9.60, 'none', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Pasar Prepacked Carrots', 'The Australian carrots are extremely crunchy.', '100% pure carrot', 0.95, 'Vegan', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Chef Chinese Spinach (Phuay Leng)', 'Freshness Guarantee for Online Orders', '100% Spinach', 1.95, 'Vegan', 100);
insert into items (name, description, ingredients, price, dietary, stock) values ('Pasar Red Chilli Padi', 'Sourced from Thailand and Vietnam.', '100% Pure Chilli Padi', 1.15, 'Vegan', 100);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Initation Crab Meat', 'Painting & Vinyl Wall Covering', '46.81', 'Drama', 25);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beef - Top Sirloin', 'Temp Fencing, Decorative Fencing and Gates', '40.21', 'Drama|Romance', 26);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Ice Cream - Fudge Bars', 'EIFS', '43.54', 'Comedy', 27);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Parsnip', 'HVAC', '19.10', 'Adventure|Crime|Drama', 28);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Sorrel - Fresh', 'Prefabricated Aluminum Metal Canopies', '10.80', 'Action|Crime|Thriller', 29);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beef - Baby, Liver', 'Fire Sprinkler System', '47.15', 'Comedy|Romance', 30);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Yoghurt Tubes', 'RF Shielding', '0.46', 'Sci-Fi|Thriller|IMAX', 31);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Cheese - Provolone', 'Granite Surfaces', '30.91', 'Animation|Comedy|Fantasy', 32);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Sauce - Chili', 'Fire Sprinkler System', '44.20', 'Adventure|Children|Fantasy', 33);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Mangostein', 'EIFS', '15.44', 'Drama|Romance', 34);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Bread - Corn Muffaleta Onion', 'Termite Control', '47.69', 'Adventure|Drama|Romance', 35);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Bowl 12 Oz - Showcase 92012', 'Landscaping & Irrigation', '33.14', 'Comedy|Drama', 36);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Bread - Flat Bread', 'Masonry & Precast', '31.33', 'Action|Adventure|Thriller', 37);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Arizona - Plum Green Tea', 'Elevator', '5.88', 'Comedy|Crime|Drama', 38);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Sauce - Caesar Dressing', 'EIFS', '13.23', 'Comedy|Drama', 39);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Pasta - Penne, Rigate, Dry', 'Rebar & Wire Mesh Install', '44.75', 'Western', 40);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Oven Mitt - 13 Inch', 'Granite Surfaces', '37.44', 'Horror|Thriller', 41);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Fruit Salad Deluxe', 'Waterproofing & Caulking', '24.73', 'Comedy', 42);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Compound - Raspberry', 'Roofing (Asphalt)', '19.44', 'Comedy|Fantasy', 43);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Dried Cranberries', 'Prefabricated Aluminum Metal Canopies', '19.65', '(no genres listed)', 44);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Turnip - Mini', 'RF Shielding', '15.04', 'Crime|Film-Noir', 45);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Cucumber - English', 'Drywall & Acoustical (FED)', '12.77', 'Sci-Fi|Thriller', 46);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Bay Leaf Ground', 'Painting & Vinyl Wall Covering', '38.62', 'Action|Thriller', 47);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Scotch - Queen Anne', 'Masonry & Precast', '48.38', 'Drama|Romance', 48);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Coffee Decaf Colombian', 'Drywall & Acoustical (MOB)', '40.12', 'Comedy|Crime', 49);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Carbonated Water - Raspberry', 'Overhead Doors', '11.06', 'Documentary', 50);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beer - Camerons Auburn', 'Drywall & Acoustical (MOB)', '30.63', 'Documentary', 51);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beef - Top Butt Aaa', 'Prefabricated Aluminum Metal Canopies', '2.27', 'Animation|Fantasy|Sci-Fi|Thriller', 52);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Rosemary - Dry', 'Hard Tile & Stone', '34.11', 'Adventure|War|Western', 53);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Juice - Apple, 500 Ml', 'Construction Clean and Final Clean', '45.73', 'Drama', 54);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Clam Nectar', 'Curb & Gutter', '34.75', 'Drama', 55);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Goldschalger', 'Plumbing & Medical Gas', '46.61', 'Comedy', 56);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Oil - Food, Lacquer Spray', 'Masonry & Precast', '12.00', 'Animation|Comedy|Musical', 57);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Tofu - Soft', 'Exterior Signage', '4.67', 'Drama|War', 58);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Tortillas - Flour, 12', 'Waterproofing & Caulking', '26.27', 'Comedy|Fantasy|Romance', 59);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Apple - Fuji', 'Ornamental Railings', '8.34', 'Drama', 60);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Lobster - Tail, 3 - 4 Oz', 'Casework', '2.16', 'Sci-Fi', 61);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Spice - Greek 1 Step', 'Fire Sprinkler System', '10.81', 'Comedy|Romance', 62);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Flour - Pastry', 'Elevator', '17.68', 'Drama', 63);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beef - Ground Lean Fresh', 'Fire Protection', '5.96', 'Comedy|Romance', 64);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Bread - Roll, Canadian Dinner', 'Temp Fencing, Decorative Fencing and Gates', '0.17', 'Horror|Thriller', 65);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Bar Mix - Lime', 'Drywall & Acoustical (MOB)', '5.28', 'Comedy|Romance', 66);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Muffin Mix - Lemon Cranberry', 'Ornamental Railings', '37.92', 'Drama', 67);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Dc - Frozen Momji', 'HVAC', '47.57', 'Comedy|Romance', 68);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Soup - Campbells, Lentil', 'Electrical', '19.84', 'Documentary', 69);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Spaghetti Squash', 'Construction Clean and Final Clean', '10.75', 'Children|Comedy', 70);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Pail With Metal Handle 16l White', 'Electrical and Fire Alarm', '29.82', 'Drama', 71);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Sterno - Chafing Dish Fuel', 'Sitework & Site Utilities', '10.12', 'Comedy|Romance', 72);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Tilapia - Fillets', 'Asphalt Paving', '22.83', 'Documentary', 73);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Sauce - Thousand Island', 'Termite Control', '14.12', 'Adventure|Children|Fantasy', 74);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Veal - Bones', 'Electrical and Fire Alarm', '11.28', 'Comedy|Drama', 75);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Wine - Sogrape Mateus Rose', 'Plumbing & Medical Gas', '32.63', 'Animation', 76);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Juice - Pineapple, 48 Oz', 'Waterproofing & Caulking', '23.99', 'Action|Romance|Sci-Fi', 77);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Wine - Beringer Founders Estate', 'Painting & Vinyl Wall Covering', '2.74', 'Horror|Sci-Fi', 78);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Chocolate - Sugar Free Semi Choc', 'Wall Protection', '42.20', 'Action|Adventure|Animation|Children|Comedy|Sci-Fi', 79);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Juice - Propel Sport', 'Granite Surfaces', '6.89', 'Drama', 80);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Pork - Smoked Kassler', 'Electrical and Fire Alarm', '4.18', 'Drama', 81);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Snails - Large Canned', 'Fire Protection', '3.66', 'Action', 82);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Red Pepper Paste', 'Painting & Vinyl Wall Covering', '33.49', 'Horror|Thriller', 83);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Appetizer - Cheese Bites', 'Wall Protection', '10.38', 'Drama|Romance', 84);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Scampi Tail', 'Sitework & Site Utilities', '25.10', 'Comedy|Drama|Romance', 85);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beef - Ox Tail, Frozen', 'Site Furnishings', '33.57', 'Comedy|Musical|Romance', 86);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Flax Seed', 'Prefabricated Aluminum Metal Canopies', '8.53', 'Comedy|Romance', 87);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Wine - Peller Estates Late', 'Wall Protection', '49.96', 'Mystery|Thriller', 88);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Oil - Olive', 'Structural & Misc Steel Erection', '26.80', 'Drama|Fantasy|War', 89);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Pepper - Chillies, Crushed', 'Painting & Vinyl Wall Covering', '25.36', 'Comedy|Romance', 90);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Juice - Tomato, 48 Oz', 'Epoxy Flooring', '18.34', 'Comedy|Thriller', 91);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beets', 'Sitework & Site Utilities', '46.72', 'Comedy|Horror|Thriller', 92);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Rabbit - Whole', 'Drywall & Acoustical (MOB)', '26.69', 'Crime|Drama|Mystery', 93);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Nut - Walnut, Pieces', 'Painting & Vinyl Wall Covering', '32.33', 'Drama|Horror|Mystery|Thriller|War', 94);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beer - Muskoka Cream Ale', 'Waterproofing & Caulking', '5.51', 'Action|Sci-Fi|Thriller', 95);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Pepper - Scotch Bonnet', 'Casework', '11.26', 'Action|Adventure|Crime|Drama|Romance', 96);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Nectarines', 'Marlite Panels (FED)', '33.73', 'Drama|Thriller', 97);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Skirt - 29 Foot', 'HVAC', '1.82', 'Comedy|Drama', 98);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Beef - Texas Style Burger', 'Curb & Gutter', '1.53', 'Crime|Film-Noir|Mystery|Thriller', 99);
-- insert into items (name, description, ingredients, price, dietary, stock) values ('Wine - Red, Black Opal Shiraz', 'Casework', '19.55', 'Comedy|Drama', 100);
